module.exports = [
    {
        src:[
            './build/validate/validate.js',
            './build/js/common/**',
            './build/js/plugin/**'
        ],
        concatName:'main.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/login.js',
            './build/js/page/login.js'
        ],
        concatName:'login.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/permission.js',
            './build/js/ui/permission-menu.js',
            './build/js/page/permission/**'
        ],
        concatName:'permission.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/channel/advert.js',
        ],
        concatName:'channel-advert.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/shake/config.js',
        ],
        concatName:'shake-config.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/shake/list.js',
        ],
        concatName:'shake-list.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/shake/prize.js',
        ],
        concatName:'shake-prize.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/bootstrap-datetimepicker.min.js',
            './build/js/ui/date.js',
            './build/js/page/shake/detail.js',
        ],
        concatName:'shake-detail.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/bootstrap-datetimepicker.min.js',
            './build/js/ui/date.js',
            './build/js/page/product/list.js',
        ],
        concatName:'product-list.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/withdraw/list.js'
        ],
        concatName:'withdraw-list.js',
        destPath:'./build/js/build/'
    },
];